Update formula_recognition.py
This version will cause error like
Traceback (most recent call last):
  File "/data1/zhangzy/DocXChain/example.py", line 15, in <module>
    from modules.formula_recognition import FormulaRecognition
  File "/data1/zhangzy/DocXChain/modules/formula_recognition.py", line 9, in <module>
    from rapid_latex_ocr import LatexOCR
ImportError: cannot import name 'LatexOCR' from 'rapid_latex_ocr' (/data1/zhangzy/anaconda3/envs/docxchain/lib/python3.9/site-packages/rapid_latex_ocr/__init__.py)
because of incorrect "LatexOCR", and should be "LaTeXOCR"